services:
  app:
    container_name: bakdrop
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - bakdrop_data:/var/lib/bakdrop
      - bakdrop_files:/fsr
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  bakdrop_data:
  bakdrop_files:
  vendor: