services:
  app:
    container_name: bakdrop
    build: .
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - "8080:80"
    environment:
      - BASE_URL=http://10.10.50.253:8080
      - FILES_PATH=/fsr
      - DEFAULT_LANG=pl
      - TZ=Europe/Warsaw

volumes:
  vendor:
